name: CI for Spring Boot

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run
jobs:
  build:
    # The type of runner to use (Ubuntu is the most common for Java projects)
    runs-on: ubuntu-latest

    # Steps to perform
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (or any version compatible with your project)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache the Maven dependencies to speed up subsequent builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Build the Spring Boot application
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Run tests
      - name: Run tests
        run: mvn test --no-transfer-progress
